72410-vpdh98
algorithm-everyday/algorithm-everyday pull request #138
Opened 2021-05-31 14:17 UTC by vpdh98

import Foundation

func _1Step(_ id:String)->String{
    return id.lowercased()
}

func _2Step(_ id:String)->String{
    return id.components(separatedBy:["~","!","@","#","$","%","^","&","*","(",")","=","+","[","{","]","}",":","?",",","<",">","/"]).joined()
}

func _3Step(_ id:String)->String{
    var returnId:String = ""
    var preChar:Character = " "
    for char in id{
        if preChar == char && char == "."{
           continue 
        }
        returnId.append(char)
        preChar = char
    }
    return returnId
}

func _4Step(_ id:String)->String{
    return id.trimmingCharacters(in: ["."])
}

func _5Step(_ id:String)->String{
    if id == ""{
        return "a"
    }
    return id
}

func _6Step(_ id:String)->String{
    var returnId:String = ""
    var idCount:Int = 0
    if id.count > 15{
        for char in id{
            if idCount > 14{
                returnId = _4Step(returnId)
                return returnId
            }
            returnId.append(char)
            idCount+=1
        }
    }
    return id 
}

func _7Step(_ id:String)->String{
    var returnId:String = id
    while returnId.count < 3{
        returnId.append(returnId.last!)
    }
    return returnId
}

func solution(_ new_id:String) -> String {
    var modifyId:String = _1Step(new_id)
    modifyId = _2Step(modifyId)
    modifyId = _3Step(modifyId)
    modifyId = _4Step(modifyId)
    modifyId = _5Step(modifyId)
    modifyId = _6Step(modifyId)
    modifyId = _7Step(modifyId)
    
    return modifyId
}

2021-06-01 12:06 UTC, gon125 requested changes
다른 분들 pull request 보고 양식 수정 부탁드립니다.

2021-06-03 13:45 UTC, gon125 approved these changes

2021-06-03 13:45 UTC, gon125 commented on programmers/72410/swift/vpdh98.swift
> +func _1Step(_ id:String)->String{
함수 명 앞에 언더바를 붙이신 이유가 있나요?

2021-06-03 13:46 UTC, merged

2021-06-04 12:58 UTC, vpdh98 commented on programmers/72410/swift/vpdh98.swift
> +func _1Step(_ id:String)->String{
직관적인 함수명을 위해 붙였습니다.