127-vpdh98
algorithm-everyday/algorithm-everyday pull request #144
Opened 2021-06-09 13:46 UTC by vpdh98

여행경로문제 다른 알고리즘

2021-06-10 01:25 UTC, gon125 requested changes
결과 화면도 같이 올려주세요.

2021-06-10 01:25 UTC, gon125 commented on programmers/43164/swift/vpdh98_ver2.swift
> +                endGame = self.gogogo(self[i].last!,&tStack,&isVisited,&visitCount,i)
여기서 endGame 이 true 이면 break 하면 퍼포먼스가 좋을 듯.
지금은 이미 찾아도 for문 다 돌고서야 나오넴

2021-06-15 11:05 UTC, gon125 approved these changes

2021-06-15 11:09 UTC, merged

2021-06-15 11:10 UTC, vpdh98 commented on programmers/43164/swift/vpdh98_ver2.swift
> +                endGame = self.gogogo(self[i].last!,&tStack,&isVisited,&visitCount,i)
하나 찾아도 갈림길에선 또 찾아야되는거 아님?

2021-06-15 11:18 UTC, gon125 commented on programmers/43164/swift/vpdh98_ver2.swift
> +                endGame = self.gogogo(self[i].last!,&tStack,&isVisited,&visitCount,i)
ㅇ? endGame true 이면 이미 최적 해 찾은거 아니야 ?

2021-06-30 14:57 UTC, vpdh98 reviewed
감자

2021-06-30 14:57 UTC, vpdh98 commented on programmers/43164/swift/vpdh98_ver2.swift
> +                endGame = self.gogogo(self[i].last!,&tStack,&isVisited,&visitCount,i)
엥 break추가하니까 더 빨라지네 왜지 감자

2021-06-30 15:02 UTC, vpdh98 commented on programmers/43164/swift/vpdh98_ver2.swift
> +                endGame = self.gogogo(self[i].last!,&tStack,&isVisited,&visitCount,i)
보이미? 무친 속도?
![image](https://user-images.githubusercontent.com/33365675/123984356-879c7e00-d9ff-11eb-8405-6791a21822ad.png)